### ISSUE TITLE
Point cloud not displaying in RVIZ

### ISSUE THREAD

**Issue by samiqmul** [rohanpsingh/ros_object_detector#1]
Hey Rohan,

Frame of the input point cloud where the data is being published is not showing up in RVIZ.
Have tried using a temporary frame but it did not work.

**Comment by rohanpsingh** [comment]
Sam, when everything is running, can you please send me the output of the following?
 $ rosnode info /find_object ?
And $rostopic echo /find_object/object_pose -n 1

**Comment by samiqmul** [comment]
Hey Rohan,

Below is the screen output from these two commands : 

![screenshot from 2018-05-03 15-06-13](https://user-images.githubusercontent.com/38887768/39581714-22108d64-4ee4-11e8-8baa-c9ee35e51b3c.png)

**Comment by rohanpsingh** [comment]
Thanks.
This seems fine.  
Are you able to visualize /find_object/object_pose in rviz?

**Comment by samiqmul** [comment]
Yes, I can see it. But it would not be displaying because of No tf data.

![screenshot from 2018-05-03 15-23-51](https://user-images.githubusercontent.com/38887768/39582571-2449dec6-4ee6-11e8-9180-a29b4152f6fb.png)

**Comment by rohanpsingh** [comment]
1. Are you even able to visualise the input point cloud topic '/kinect2/qhd/points' in rviz? Are you able to visualize any data from kinect in rviz (like rgb image etc.) ? 
2. What are the frames shown by the drop down list of 'Fixed Frame' in global options?
3. Try choosing(if available in the drop down list)  or typing 'kinect2_rgb_optical_frame' .

**Comment by samiqmul** [comment]
1. Yes, I get the option of '/kinect2/qhd/points' in drop down list for PointsCloud2. I do not get input of kinect in Camera Display tab (but a image can be seen under the Image Display Tab).
2. 'Fixed Frame' does not show any option in drop down list. (This might be the main problem for data to be not displaying).

What bridge are you using for kinect to work in ROS ?

**Comment by rohanpsingh** [comment]
I generally use freenect. You can try to use the same, I think this could be the problem.
wiki.ros.org/freenect_launch

**Comment by samiqmul** [comment]
I am using the same, libfreenect2 for this version of kinect

**Comment by samiqmul** [comment]
Hey Rohan, thanks for all the guidance. 
I am able to get some output from the RVIZ now after changing the title of the frame in the tf file. 

![screenshot from 2018-05-03 17-13-56](https://user-images.githubusercontent.com/38887768/39589371-e8de6a86-4ef5-11e8-8488-564e3574f861.png)

**Comment by rohanpsingh** [comment]
Great! 
I am closing this for now.
